[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.26"
optimizer = true
optimizer_runs = 800
evm_version = "cancun"

[lint]
severity = ["high", "med"]

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"
multiline_func_header = "params_first"
quote_style = "double"
number_underscore = "thousands"
single_line_statement_blocks = "preserve"

[rpc_endpoints]
mainnet   = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
optimism  = "https://opt-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
bnb       = "https://bnb-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
unichain  = "https://unichain-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
base      = "https://base-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
arbitrum  = "https://arb-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"

[etherscan]
mainnet   = { key = "${ETHERSCAN_API_KEY}", chain = 1,     url = "https://api.etherscan.io/v2/api?chainid=1" }
optimism  = { key = "${ETHERSCAN_API_KEY}", chain = 10,    url = "https://api.etherscan.io/v2/api?chainid=10" }
bnb       = { key = "${ETHERSCAN_API_KEY}", chain = 56,    url = "https://api.etherscan.io/v2/api?chainid=56" }
unichain  = { key = "${ETHERSCAN_API_KEY}", chain = 130,   url = "https://api.etherscan.io/v2/api?chainid=130" }
base      = { key = "${ETHERSCAN_API_KEY}", chain = 8453,  url = "https://api.etherscan.io/v2/api?chainid=8453" }
arbitrum  = { key = "${ETHERSCAN_API_KEY}", chain = 42161, url = "https://api.etherscan.io/v2/api?chainid=42161" }
